"""Calc-trace pattern: every output number carries the formula + inputs that produced it.

This is the core design constraint (SPEC §2): the trace is generated by the same code
that computes the value, so the displayed equation can never drift from what actually ran.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field


@dataclass
class Traced:
    value: float
    label: str
    formula: str  # human-readable, e.g. "se_base * 0.124"
    inputs: dict[str, float] = field(default_factory=dict)
    method: str = "exact"  # "exact" | "approximation"
    note: str = ""  # e.g. "ignores SS wage cap"
    children: list["Traced"] = field(default_factory=list)

    def explain(self, indent: int = 0) -> str:
        """Render the trace tree: value, formula with inputs substituted, approximation notes."""
        pad = "  " * indent
        flag = " ⚠" if self.method == "approximation" else ""
        substituted = _substitute(self.formula, self.inputs)
        lines = [f"{pad}{self.label}: {self.value:,.2f}{flag}"]
        if self.formula:
            lines.append(f"{pad}  = {self.formula}")
            if substituted != self.formula:
                lines.append(f"{pad}  = {substituted}")
        if self.note:
            lines.append(f"{pad}  note: {self.note}")
        for child in self.children:
            lines.append(child.explain(indent + 1))
        return "\n".join(lines)

    def recompute(self) -> float:
        """Re-evaluate the formula with the recorded inputs.

        Used by the property test that guarantees trace == computation. Only safe
        arithmetic names are exposed; formulas that call helpers (brackets(), etc.)
        are marked unverifiable by returning NaN.
        """
        safe = {"__builtins__": {}, "min": min, "max": max, "abs": abs}
        safe.update(self.inputs)
        try:
            return float(eval(self.formula, safe))  # noqa: S307 - sandboxed, internal formulas only
        except (NameError, TypeError, SyntaxError, ZeroDivisionError):
            return math.nan

    def verifiable(self) -> bool:
        """True if recompute() can evaluate this formula from its inputs alone."""
        return not math.isnan(self.recompute())


def _substitute(formula: str, inputs: dict[str, float]) -> str:
    """Replace input names with their values for the 'with numbers' rendering.

    Longest names first so e.g. `se_base` isn't partially clobbered by `se`.
    """
    import re

    out = formula
    for name in sorted(inputs, key=len, reverse=True):
        out = re.sub(rf"\b{re.escape(name)}\b", f"{inputs[name]:,.2f}", out)
    return out
